<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\System\Company;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies = Company::all();
        $company1 = $companies->first();
        $company2 = $companies->last();

        // Obter categorias por empresa
        $pizzasCat1 = Category::where('company_id', $company1->id)->where('slug', 'pizzas')->first();
        $frutosCat1 = Category::where('company_id', $company1->id)->where('slug', 'frutos-do-mar')->first();
        $bebidasCat1 = Category::where('company_id', $company1->id)->where('slug', 'bebidas')->first();
        $sobremesasCat1 = Category::where('company_id', $company1->id)->where('slug', 'sobremesas')->first();
        $saladasCat1 = Category::where('company_id', $company1->id)->where('slug', 'saladas')->first();

        $pizzasCat2 = Category::where('company_id', $company2->id)->where('slug', 'pizzas')->first();
        $bebidasCat2 = Category::where('company_id', $company2->id)->where('slug', 'bebidas')->first();
        $sobremesasCat2 = Category::where('company_id', $company2->id)->where('slug', 'sobremesas')->first();
        $entradasCat2 = Category::where('company_id', $company2->id)->where('slug', 'entradas')->first();
        $cafesCat2 = Category::where('company_id', $company2->id)->where('slug', 'cafes')->first();

        // Produtos para Restaurante Sabores do Mar
        $productsCompany1 = [
            [
                'subcategory_id' => 2,
                'category_id' => $pizzasCat1->id,
                'name' => 'Pizza Margherita',
                'slug' => 'pizza-margherita',
                'description' => 'Pizza clássica com molho de tomate, mozzarella e manjericão fresco',
                'price' => 850.00,
                'cost' => 320.00,
                'type' => 'composed',
                'stock_quantity' => 25.0,
                'min_level' => 5.0,
                'cost_per_unit' => 320.00,
                'barcode' => '7891234567890',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $pizzasCat1->id,
                'name' => 'Pizza Portuguesa',
                'slug' => 'pizza-portuguesa',
                'description' => 'Pizza com presunto, ovos, cebola, azeitonas e queijo',
                'price' => 1100.00,
                'cost' => 450.00,
                'type' => 'composed',
                'stock_quantity' => 18.0,
                'min_level' => 3.0,
                'cost_per_unit' => 450.00,
                'barcode' => '7891234567891',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $frutosCat1->id,
                'name' => 'Camarão Grelhado',
                'slug' => 'camarao-grelhado',
                'description' => 'Camarões grelhados com alho e ervas finas',
                'price' => 1450.00,
                'cost' => 680.00,
                'type' => 'simple',
                'stock_quantity' => 12.0,
                'min_level' => 2.0,
                'cost_per_unit' => 680.00,
                'barcode' => '7891234567892',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $frutosCat1->id,
                'name' => 'Peixe Grelhado do Dia',
                'slug' => 'peixe-grelhado-do-dia',
                'description' => 'Peixe fresco grelhado com legumes da época',
                'price' => 1200.00,
                'cost' => 520.00,
                'type' => 'simple',
                'stock_quantity' => 8.0,
                'min_level' => 2.0,
                'cost_per_unit' => 520.00,
                'barcode' => '7891234567893',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $bebidasCat1->id,
                'name' => 'Coca-Cola 500ml',
                'slug' => 'coca-cola-500ml',
                'description' => 'Refrigerante Coca-Cola gelado',
                'price' => 120.00,
                'cost' => 45.00,
                'type' => 'simple',
                'stock_quantity' => 3.0,
                'min_level' => 10.0,
                'cost_per_unit' => 45.00,
                'barcode' => '7891000000123',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ]
        ];

        // Produtos para Pizzaria Milano
        $productsCompany2 = [
            [
                'subcategory_id' => 1,
                'category_id' => $pizzasCat2->id,
                'name' => 'Pizza Pepperoni',
                'slug' => 'pizza-pepperoni',
                'description' => 'Pizza com molho de tomate, mozzarella e pepperoni',
                'price' => 950.00,
                'cost' => 380.00,
                'type' => 'composed',
                'stock_quantity' => 20.0,
                'min_level' => 4.0,
                'cost_per_unit' => 380.00,
                'barcode' => '7892345678901',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company2->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $pizzasCat2->id,
                'name' => 'Pizza Quattro Stagioni',
                'slug' => 'pizza-quattro-stagioni',
                'description' => 'Pizza dividida em quatro sabores diferentes',
                'price' => 1200.00,
                'cost' => 480.00,
                'type' => 'composed',
                'stock_quantity' => 15.0,
                'min_level' => 3.0,
                'cost_per_unit' => 480.00,
                'barcode' => '7892345678902',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company2->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $sobremesasCat2->id,
                'name' => 'Tiramisu',
                'slug' => 'tiramisu',
                'description' => 'Sobremesa italiana clássica com café e mascarpone',
                'price' => 380.00,
                'cost' => 150.00,
                'type' => 'simple',
                'stock_quantity' => 6.0,
                'min_level' => 2.0,
                'cost_per_unit' => 150.00,
                'barcode' => '7892345678903',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company2->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $entradasCat2->id,
                'name' => 'Pão de Alho',
                'slug' => 'pao-de-alho',
                'description' => 'Pão italiano com alho e ervas',
                'price' => 280.00,
                'cost' => 95.00,
                'type' => 'simple',
                'stock_quantity' => 12.0,
                'min_level' => 5.0,
                'cost_per_unit' => 95.00,
                'barcode' => '7892345678904',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company2->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $cafesCat2->id,
                'name' => 'Espresso Italiano',
                'slug' => 'espresso-italiano',
                'description' => 'Café espresso autêntico italiano',
                'price' => 180.00,
                'cost' => 35.00,
                'type' => 'simple',
                'stock_quantity' => 2, // Produto sem controle de stock
                'min_level' => 0,
                'cost_per_unit' => 35.00,
                'barcode' => '7892345678905',
                'track_stock' => false,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company2->id,
            ],
              // Pizzas adicionais
            [
                'subcategory_id' => 1,
                'category_id' => $pizzasCat1->id,
                'name' => 'Pizza Calabresa',
                'slug' => 'pizza-calabresa',
                'description' => 'Pizza com calabresa, cebola e queijo',
                'price' => 950.00,
                'cost' => 400.00,
                'type' => 'composed',
                'stock_quantity' => 20,
                'min_level' => 5,
                'cost_per_unit' => 400.00,
                'barcode' => '7891234567894',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $pizzasCat1->id,
                'name' => 'Pizza Frango com Catupiry',
                'slug' => 'pizza-frango-catupiry',
                'description' => 'Pizza com frango desfiado e catupiry',
                'price' => 1000.00,
                'cost' => 420.00,
                'type' => 'composed',
                'stock_quantity' => 18,
                'min_level' => 4,
                'cost_per_unit' => 420.00,
                'barcode' => '7891234567895',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $pizzasCat1->id,
                'name' => 'Pizza Quatro Queijos',
                'slug' => 'pizza-quatro-queijos',
                'description' => 'Pizza com quatro tipos de queijos',
                'price' => 1150.00,
                'cost' => 500.00,
                'type' => 'composed',
                'stock_quantity' => 22,
                'min_level' => 5,
                'cost_per_unit' => 500.00,
                'barcode' => '7891234567896',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $pizzasCat1->id,
                'name' => 'Pizza Pepperoni',
                'slug' => 'pizza-pepperoni',
                'description' => 'Pizza com pepperoni e queijo mozzarella',
                'price' => 1050.00,
                'cost' => 430.00,
                'type' => 'composed',
                'stock_quantity' => 17,
                'min_level' => 4,
                'cost_per_unit' => 430.00,
                'barcode' => '7891234567897',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            // Frutos do mar adicionais
            [
                'subcategory_id' => 1,
                'category_id' => $frutosCat1->id,
                'name' => 'Camarão ao Molho de Coco',
                'slug' => 'camarao-molho-coco',
                'description' => 'Camarões ao molho de coco com especiarias',
                'price' => 1600.00,
                'cost' => 700.00,
                'type' => 'simple',
                'stock_quantity' => 14,
                'min_level' => 3,
                'cost_per_unit' => 700.00,
                'barcode' => '7891234567898',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $frutosCat1->id,
                'name' => 'Peixe à Delícia',
                'slug' => 'peixe-delicia',
                'description' => 'Peixe fresco com molho especial da casa',
                'price' => 1400.00,
                'cost' => 600.00,
                'type' => 'simple',
                'stock_quantity' => 9,
                'min_level' => 2,
                'cost_per_unit' => 600.00,
                'barcode' => '7891234567899',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 1,
                'category_id' => $frutosCat1->id,
                'name' => 'Lula à Provençal',
                'slug' => 'lula-provencal',
                'description' => 'Lula grelhada com ervas finas',
                'price' => 1300.00,
                'cost' => 550.00,
                'type' => 'simple',
                'stock_quantity' => 10,
                'min_level' => 2,
                'cost_per_unit' => 550.00,
                'barcode' => '7891234567900',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            // Bebidas adicionais
            [
                'subcategory_id' => 2,
                'category_id' => $bebidasCat1->id,
                'name' => 'Água Mineral 500ml',
                'slug' => 'agua-mineral-500ml',
                'description' => 'Água mineral gelada',
                'price' => 50.00,
                'cost' => 20.00,
                'type' => 'simple',
                'stock_quantity' => 30,
                'min_level' => 10,
                'cost_per_unit' => 20.00,
                'barcode' => '7891000000126',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 2,
                'category_id' => $bebidasCat1->id,
                'name' => 'Suco de Manga 300ml',
                'slug' => 'suco-manga-300ml',
                'description' => 'Suco natural de manga',
                'price' => 90.00,
                'cost' => 35.00,
                'type' => 'simple',
                'stock_quantity' => 25,
                'min_level' => 5,
                'cost_per_unit' => 35.00,
                'barcode' => '7891000000127',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 2,
                'category_id' => $bebidasCat1->id,
                'name' => 'Cerveja Lata 350ml',
                'slug' => 'cerveja-lata-350ml',
                'description' => 'Cerveja gelada em lata',
                'price' => 150.00,
                'cost' => 60.00,
                'type' => 'simple',
                'stock_quantity' => 40,
                'min_level' => 10,
                'cost_per_unit' => 60.00,
                'barcode' => '7891000000128',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company1->id,
            ],
            // Sobremesas
            [
                'subcategory_id' => 2,
                'category_id' => $sobremesasCat1->id ?? $pizzasCat1->id,
                'name' => 'Pudim de Leite',
                'slug' => 'pudim-leite',
                'description' => 'Pudim de leite condensado cremoso',
                'price' => 100.00,
                'cost' => 40.00,
                'type' => 'simple',
                'stock_quantity' => 15,
                'min_level' => 5,
                'cost_per_unit' => 40.00,
                'barcode' => '7891000000129',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => true,
                'company_id' => $company1->id,
            ],
            [
                'subcategory_id' => 2,
                'category_id' => $sobremesasCat1->id ?? $pizzasCat1->id,
                'name' => 'Sorvete Chocolate',
                'slug' => 'sorvete-chocolate',
                'description' => 'Sorvete sabor chocolate',
                'price' => 120.00,
                'cost' => 50.00,
                'type' => 'simple',
                'stock_quantity' => 12,
                'min_level' => 5,
                'cost_per_unit' => 50.00,
                'barcode' => '7891000000130',
                'track_stock' => true,
                'is_available' => true,
                'is_active' => true,
                'is_featured' => false,
                'company_id' => $company1->id,
            ],
        ];

        $allProducts = array_merge($productsCompany1, $productsCompany2);

        foreach ($allProducts as $productData) {
            Product::create($productData);
        }
    }
}
